import React from 'react'
import './globals.css'
import localFont from 'next/font/local'

import type { Metadata } from 'next'

const pangramSans = localFont({
  src: [
    {
      path: './fonts/PPPangramSans-Light.otf',
      weight: '200',
      style: 'ligth'
    },
    {
      path: './fonts/PPPangramSans-Medium.otf',
      weight: '400',
      style: 'medium'
    },
    {
      path: './fonts/PPPangramSans-Bold.otf',
      weight: '800',
      style: 'bold'
    }
  ],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Dycsa - Casa Grande Laplace',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={pangramSans.className}>
        {children}
      </body>
    </html>
  )
}
